/* -*- Mode: C; tab-width: 8; indent-tabs-mode: t; c-basic-offset: 8 -*- */
/*
 * Interface for Yelp
 *
 */

#include <Bonobo.idl>

module GNOME {
        interface Yelp : Bonobo::Unknown {
		typedef sequence<string>  WindowList;

                void       newWindow  (in string url, in string time);
		WindowList getWindows ();
        };
};




